### PR TITLE
Adding missing word

### PR DESCRIPTION
**Pull request by tinyapps**
Original: https://archive.org/details/fiveweeksinballo00vern/page/234/mode/1up (page 234, first sentence)

### CODE REVIEW

**Comment by acabal** [comment]
Thanks!

**Comment by tinyapps** [comment]
Thank _you_, Alex! I just stumbled onto another typo and was wondering whether I should just keep a record of them and submit all at once in a single PR or keep submitting them individually?

**Comment by acabal** [comment]
You can put them all into one PR once you're done. I think that will be easier for everyone. Thanks!

**Comment by tinyapps** [comment]
Will do - thanks!

**Pull request merged**
